### PR TITLE
feat(team): add optional bio field in team members.

### LINKED ISSUE #151: Suggestion: add a bio for members of the team
For now, we can provide a name and optionally a role and a photo url. Can we add an optional field to provide a short bio (like a speaker) for members of the event team?

(Probably a good first issue)

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #151

### CODE REVIEW

**Comment by HugoGresse** [comment]
Merci Gérard ! Bon Noël !

**Comment by HugoGresse** [comment]
I'm not sure the bio field would br added to the status api though

**Comment by GerardPaligot** [comment]
A toi aussi Hugo! ^^

**Comment by GerardPaligot** [comment]
@HugoGresse For information, it is ok in the static api. :)

**Pull request merged**
